In [1]:
import pandas as pd

In [8]:
df_a = pd.read_excel("../input/発注書A①.xlsx")
df_b = pd.read_csv("../input/発注書B①.csv")

In [9]:
df_a.head()

         発注日    商品名  数量
0 2025-10-01  キーボード  10
1 2025-10-01    マウス  15
2 2025-10-01   モニター   5
3 2025-10-02  キーボード  12
4 2025-10-02    マウス  18

In [10]:
df_a.columns

Index(['発注日', '商品名', '数量'], dtype='object')

In [11]:
df_a.dtypes

発注日    datetime64[ns]
商品名            object
数量              int64
dtype: object

In [12]:
df_b.head()

        発注日付  個数    製品名
0  令和7年10月1日   8  キーボード
1  令和7年10月1日  10    マウス
2  令和7年10月1日   3  スピーカー
3  令和7年10月2日  12  キーボード
4  令和7年10月2日  15    マウス

In [13]:
df_b.columns

Index(['発注日付', '個数', '製品名'], dtype='object')

In [14]:
df_b.dtypes

発注日付    object
個数       int64
製品名     object
dtype: object

In [15]:
df_a_std = df_a.rename(columns={
    "発注日": "order_date",
    "商品名": "product_name",
    "数量": "quantity"
})

In [16]:
df_b_std = df_b.rename(columns={
    "発注日付": "order_date",
    "製品名": "product_name",
    "個数": "quantity"
})

In [17]:
import re

def convert_reiwa_date(text):
    match = re.match(r"令和(\d+)年(\d+)月(\d+)日", text)

    reiwa_year = int(match.group(1))
    month = int(match.group(2))
    day = int(match.group(3))

    year = reiwa_year + 2018

    return pd.Timestamp(year=year, month=month, day=day)

In [18]:
convert_reiwa_date("令和7年10月1日")

Timestamp('2025-10-01 00:00:00')

In [19]:
df_b_std["order_date"] = df_b_std["order_date"].apply(convert_reiwa_date)

In [20]:
df_b_std.dtypes

order_date      datetime64[ns]
quantity                 int64
product_name            object
dtype: object

In [23]:
df_b_std.head()

  order_date  quantity product_name
0 2025-10-01         8        キーボード
1 2025-10-01        10          マウス
2 2025-10-01         3        スピーカー
3 2025-10-02        12        キーボード
4 2025-10-02        15          マウス

In [22]:
df_b.columns

Index(['発注日付', '個数', '製品名'], dtype='object')

In [24]:
df_a_std.dtypes

order_date      datetime64[ns]
product_name            object
quantity                 int64
dtype: object

In [25]:
df_all = pd.concat(
    [df_a_std, df_b_std],
    ignore_index=True
)

In [26]:
df_all.head()

  order_date product_name  quantity
0 2025-10-01        キーボード        10
1 2025-10-01          マウス        15
2 2025-10-01         モニター         5
3 2025-10-02        キーボード        12
4 2025-10-02          マウス        18

In [27]:
df_all.tail()

   order_date product_name  quantity
25 2025-10-02        スピーカー         4
26 2025-10-03        キーボード        10
27 2025-10-03          マウス        12
28 2025-10-03        スピーカー         6
29 2025-10-04        キーボード        11

In [28]:
df_all.shape

(30, 3)

In [29]:
df_all.dtypes

order_date      datetime64[ns]
product_name            object
quantity                 int64
dtype: object

In [1]:
import pandas as pd
import re

def convert_reiwa_date(text):
    match = re.match(r"令和(\d+)年(\d+)月(\d+)日", text)

    reiwa_year = int(match.group(1))
    month = int(match.group(2))
    day = int(match.group(3))

    year = reiwa_year + 2018

    return pd.Timestamp(year=year, month=month, day=day)

df_a = pd.read_excel("../input/発注書A①.xlsx")
df_b = pd.read_csv("../input/発注書B①.csv")

df_a_std = df_a.rename(columns={
    "発注日": "order_date",
    "商品名": "product_name",
    "数量": "quantity"
})
df_b_std = df_b.rename(columns={
    "発注日付": "order_date",
    "製品名": "product_name",
    "個数": "quantity"
})

df_b_std["order_date"] = df_b_std["order_date"].apply(convert_reiwa_date)

df_all = pd.concat(
    [df_a_std, df_b_std],
    ignore_index=True
)

In [2]:
df_summary = (
    df_all
    .groupby(["order_date", "product_name"], as_index=False)["quantity"]
    .sum()
)

In [4]:
df_summary.head(10)

  order_date product_name  quantity
0 2025-10-01        キーボード        18
1 2025-10-01        スピーカー         3
2 2025-10-01          マウス        25
3 2025-10-01         モニター         5
4 2025-10-02        キーボード        24
5 2025-10-02        スピーカー         4
6 2025-10-02          マウス        33
7 2025-10-02         モニター         6
8 2025-10-03        キーボード        19
9 2025-10-03        スピーカー         6

In [10]:
import pandas as pd
import re

def convert_reiwa_date(text):
    match = re.match(r"令和(\d+)年(\d+)月(\d+)日", text)

    reiwa_year = int(match.group(1))
    month = int(match.group(2))
    day = int(match.group(3))

    year = reiwa_year + 2018

    return pd.Timestamp(year=year, month=month, day=day)

df_a1 = pd.read_excel("../input/発注書A①.xlsx")
df_a2 = pd.read_excel("../input/発注書A②.xlsx")
df_b = pd.read_csv("../input/発注書B①.csv")

df_a_std1 = df_a1.rename(columns={
    "発注日": "order_date",
    "商品名": "product_name",
    "数量": "quantity"
})
df_a_std2 = df_a2.rename(columns={
    "発注日": "order_date",
    "商品名": "product_name",
    "数量": "quantity"
})
df_b_std = df_b.rename(columns={
    "発注日付": "order_date",
    "製品名": "product_name",
    "個数": "quantity"
})

df_b_std["order_date"] = df_b_std["order_date"].apply(convert_reiwa_date)

df_all = pd.concat(
    [df_a_std1, df_a_std2, df_b_std],
    ignore_index=True
)

df_summary = (
    df_all
    .groupby(["order_date", "product_name"], as_index=False)["quantity"]
    .sum()
)

In [1]:
import pandas as pd
import re
from openpyxl import load_workbook

report_path = "../input/製品別売上レポート.xlsx"
output_path = "../output/製品別売上レポート.xlsx"

def convert_reiwa_date(text):
    match = re.match(r"令和(\d+)年(\d+)月(\d+)日", text)

    reiwa_year = int(match.group(1))
    month = int(match.group(2))
    day = int(match.group(3))

    year = reiwa_year + 2018

    return pd.Timestamp(year=year, month=month, day=day)

a_files = [
    "../input/発注書A①.xlsx",
    "../input/発注書A②.xlsx",
]
b_files = [
    "../input/発注書B①.csv",
    "../input/発注書B②.csv",
    "../input/発注書B③.csv"
]

a_dfs = []
b_dfs = []

for file in a_files:
    a_df = pd.read_excel(file)
    a_df = a_df.rename(columns={
        "発注日": "order_date",
        "商品名": "product_name",
        "数量": "quantity"
    })
    a_dfs.append(a_df)
    
for file in b_files:
    b_df = pd.read_csv(file)
    b_df = b_df.rename(columns={
        "発注日付": "order_date",
        "製品名": "product_name",
        "個数": "quantity"
    })
    b_df["order_date"] = b_df["order_date"].apply(convert_reiwa_date)

    b_dfs.append(b_df)

df_all = pd.concat(a_dfs + b_dfs,ignore_index=True)

df_summary = (
    df_all
    .groupby(["order_date", "product_name"], as_index=False)["quantity"]
    .sum()
)

wb = load_workbook(report_path)
ws = wb.active

for row_index, row in enumerate(df_summary.itertuples(index=False), start=2):
    date_cell = ws.cell(row=row_index, column=1, value=row.order_date)
    date_cell.number_format = "yyyy/mm/dd"

    ws.cell(row=row_index, column=2, value=row.product_name)
    ws.cell(row=row_index, column=3, value=row.quantity)

wb.save(output_path)

In [2]:
import pandas as pd
import re
from copy import copy
from openpyxl import load_workbook

report_path = "../input/製品別売上レポート.xlsx"
output_path = "../output/製品別売上レポート.xlsx"

def convert_reiwa_date(text):
    match = re.match(r"令和(\d+)年(\d+)月(\d+)日", text)

    reiwa_year = int(match.group(1))
    month = int(match.group(2))
    day = int(match.group(3))

    year = reiwa_year + 2018

    return pd.Timestamp(year=year, month=month, day=day)

a_files = [
    "../input/発注書A①.xlsx",
    "../input/発注書A②.xlsx",
]
b_files = [
    "../input/発注書B①.csv",
    "../input/発注書B②.csv",
    "../input/発注書B③.csv"
]

a_dfs = []
b_dfs = []

for file in a_files:
    a_df = pd.read_excel(file)
    a_df = a_df.rename(columns={
        "発注日": "order_date",
        "商品名": "product_name",
        "数量": "quantity"
    })
    a_dfs.append(a_df)
    
for file in b_files:
    b_df = pd.read_csv(file)
    b_df = b_df.rename(columns={
        "発注日付": "order_date",
        "製品名": "product_name",
        "個数": "quantity"
    })
    b_df["order_date"] = b_df["order_date"].apply(convert_reiwa_date)

    b_dfs.append(b_df)

df_all = pd.concat(a_dfs + b_dfs,ignore_index=True)

df_summary = (
    df_all
    .groupby(["order_date", "product_name"], as_index=False)["quantity"]
    .sum()
)

wb = load_workbook(report_path)
ws = wb.active

start_row = 2
template_end_row = 21

# 通常行と最終行の書式を保存
normal_styles = []
last_styles = []

for col in range(1, 4):
    normal_cell = ws.cell(row=2, column=col)
    last_cell = ws.cell(row=21, column=col)

    normal_styles.append({
        "font": copy(normal_cell.font),
        "fill": copy(normal_cell.fill),
        "border": copy(normal_cell.border),
        "alignment": copy(normal_cell.alignment),
        "number_format": normal_cell.number_format,
    })

    last_styles.append({
        "font": copy(last_cell.font),
        "fill": copy(last_cell.fill),
        "border": copy(last_cell.border),
        "alignment": copy(last_cell.alignment),
        "number_format": last_cell.number_format,
    })

last_data_row = start_row + len(df_summary) - 1

for row_index, row in enumerate(
    df_summary.itertuples(index=False),
    start=start_row
):
    values = [
        row.order_date,
        row.product_name,
        row.quantity,
    ]

    for col_index, value in enumerate(values, start=1):
        cell = ws.cell(
            row=row_index,
            column=col_index,
            value=value
        )

        # 通常行の書式
        style = normal_styles[col_index - 1]

        cell.font = copy(style["font"])
        cell.fill = copy(style["fill"])
        cell.border = copy(style["border"])
        cell.alignment = copy(style["alignment"])
        cell.number_format = style["number_format"]

    # 日付だけ表示形式を指定
    ws.cell(
        row=row_index,
        column=1
    ).number_format = "yyyy/mm/dd"

for col_index in range(1, 4):
    cell = ws.cell(
        row=last_data_row,
        column=col_index
    )

    style = last_styles[col_index - 1]

    cell.border = copy(style["border"])

wb.save(output_path)

In [6]:
df_summary

   order_date product_name  quantity
0  2025-10-01        キーボード        18
1  2025-10-01        スピーカー         3
2  2025-10-01          マウス        25
3  2025-10-01         モニター         5
4  2025-10-02        キーボード        24
5  2025-10-02        スピーカー         4
6  2025-10-02          マウス        33
7  2025-10-02         モニター         6
8  2025-10-03        キーボード        19
9  2025-10-03        スピーカー         6
10 2025-10-03          マウス        26
11 2025-10-03         モニター         8
12 2025-10-04        キーボード        22
13 2025-10-04          マウス        16
14 2025-10-04         モニター         7
15 2025-10-05        キーボード        13
16 2025-10-05          マウス        19
17 2025-10-05         モニター         9
18 2025-10-06        キーボード        14
19 2025-10-06          マウス        20
20 2025-10-06         モニター        10
21 2025-10-07        キーボード        10
22 2025-10-07          マウス        15

In [1]:
import pandas as pd
import re
from copy import copy
from openpyxl import load_workbook

report_path = "../input/製品別売上レポート.xlsx"
output_path = "../output/製品別売上レポート.xlsx"

def convert_reiwa_date(text):
    match = re.match(r"令和(\d+)年(\d+)月(\d+)日", text)

    reiwa_year = int(match.group(1))
    month = int(match.group(2))
    day = int(match.group(3))

    year = reiwa_year + 2018

    return pd.Timestamp(year=year, month=month, day=day)

a_files = [
    "../input/発注書A①.xlsx"
]
b_files = [
    "../input/発注書B①.csv"
]

a_dfs = []
b_dfs = []

for file in a_files:
    a_df = pd.read_excel(file)
    a_df = a_df.rename(columns={
        "発注日": "order_date",
        "商品名": "product_name",
        "数量": "quantity"
    })
    a_dfs.append(a_df)
    
for file in b_files:
    b_df = pd.read_csv(file)
    b_df = b_df.rename(columns={
        "発注日付": "order_date",
        "製品名": "product_name",
        "個数": "quantity"
    })
    b_df["order_date"] = b_df["order_date"].apply(convert_reiwa_date)

    b_dfs.append(b_df)

df_all = pd.concat(a_dfs + b_dfs,ignore_index=True)

df_summary = (
    df_all
    .groupby(["order_date", "product_name"], as_index=False)["quantity"]
    .sum()
)

wb = load_workbook(report_path)
ws = wb.active

start_row = 2
template_end_row = 21

# 通常行と最終行の書式を保存
normal_styles = []
last_styles = []

for col in range(1, 4):
    normal_cell = ws.cell(row=2, column=col)
    last_cell = ws.cell(row=21, column=col)

    normal_styles.append({
        "font": copy(normal_cell.font),
        "fill": copy(normal_cell.fill),
        "border": copy(normal_cell.border),
        "alignment": copy(normal_cell.alignment),
        "number_format": normal_cell.number_format,
    })

    last_styles.append({
        "font": copy(last_cell.font),
        "fill": copy(last_cell.fill),
        "border": copy(last_cell.border),
        "alignment": copy(last_cell.alignment),
        "number_format": last_cell.number_format,
    })

last_data_row = start_row + len(df_summary) - 1

for row_index, row in enumerate(
    df_summary.itertuples(index=False),
    start=start_row
):
    values = [
        row.order_date,
        row.product_name,
        row.quantity,
    ]

    for col_index, value in enumerate(values, start=1):
        cell = ws.cell(
            row=row_index,
            column=col_index,
            value=value
        )

        # 通常行の書式
        style = normal_styles[col_index - 1]

        cell.font = copy(style["font"])
        cell.fill = copy(style["fill"])
        cell.border = copy(style["border"])
        cell.alignment = copy(style["alignment"])
        cell.number_format = style["number_format"]

    # 日付だけ表示形式を指定
    ws.cell(
        row=row_index,
        column=1
    ).number_format = "yyyy/mm/dd"

for col_index in range(1, 4):
    cell = ws.cell(
        row=last_data_row,
        column=col_index
    )

    style = last_styles[col_index - 1]

    cell.border = copy(style["border"])

wb.save(output_path)